# Generated by Django 2.2.16 on 2022-01-19 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_commentpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
